### ISSUE TITLE
how to set XR_API_LAYER_PATH environmental variable？

### ISSUE THREAD

**Issue by SlimSnow** [KhronosGroup/OpenXR-SDK-Source#89] opened 2019-07-30 02:50 UTC
My OS is windows,I set XR_API_LAYER_PATH like this

"D:\OpenXR-SDK-Source-master\build\src\tests\loader_test\resources\layers\XrApiLayer_test.json"  

`bool FileSysUtilsPathExists(const std::string& path) { return (1 == PathFileExistsW(utf8_to_wide(path).c_str())); }` return false,I can not load the test apilayer.

And then I set XR_API_LAYER_PATH like this "D:\OpenXR-SDK-Source-master\build\src\tests\loader_test\resources\layers"  I get INVALID_HANDLE_VALUE at here

```c++
bool FileSysUtilsFindFilesInPath(const std::string& path, std::vector<std::string>& files) {
    WIN32_FIND_DATAW file_data;
    HANDLE file_handle = FindFirstFileW(utf8_to_wide(path).c_str(), &file_data);
    if (file_handle != INVALID_HANDLE_VALUE) {
        do {
            if (!(file_data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)) {
                files.push_back(wide_to_utf8(file_data.cFileName));
            }
        } while (FindNextFileW(file_handle, &file_data));
        return true;
    }
    return false;
}
```

the problem is when I pass my path to function "CopyIncludedPaths" ,this function change my path append "\\"   behind it.What ever I set XR_API_LAYER_PATH environmental variable is a json file path or a directory .And how should I set XR_API_LAYER_PATH environmental variable？

**Comment by julianeisel** [comment] 2019-07-31 22:10
I can confirm this issue. Using `XR_API_LAYER_PATH` doesn't work at all on Windows, neither with a directory nor with a file path. From what I can tell this is the only way to enable layers on Windows.

In other words, layers can not be enabled on Windows at all, which seems like a rather critical issue to me.
I'm happy to work on a fix myself, but it'll have to wait for a few days.

**Comment by SlimSnow** [comment] 2019-08-01 09:14
@julianeisel  I am not sure that is a bug or I use this environmental variable in a wrong way.For now ,I think there are something wrong in this part of loader.Hope they can find and fix it.

**Comment by SlimSnow** [comment] 2019-08-01 09:19
@daveh-lunarg please check this issue is a bug or not?Just like @julianeisel  said "Using XR_API_LAYER_PATH doesn't work at all on Windows, neither with a directory nor with a file path. From what I can tell this is the only way to enable layers on Windows.

In other words, layers can not be enabled on Windows at all, which seems like a rather critical issue to me."

**Comment by rpavlik** [comment] 2019-11-22 23:25
Assigning to brad to test/confirm.

**Comment by bradgrantham-lunarg** [comment] 2019-11-22 23:27
I believe there is a change pending on this.  I'll spend a minute tidying that up to see if it can get some upvotes.

**Comment by bradgrantham-lunarg** [comment] 2019-11-23 00:38
@SlimSnow, @julianeisel, `XR_API_LAYER_PATH `should be a list of paths to JSON manifest files for API layers, separated by the "path separator", which is `;` on Windows.  as an example, I'm currently running with these environment variables in Visual Studio's "Properties -> Debugging -> Environment":
```
XR_LOADER_DEBUG=all
XR_ENABLE_API_LAYERS=XR_APILAYER_LUNARG_api_dump
XR_API_LAYER_PATH=c:\\Users\\grantham\\trees\\OpenXR\\build\\src\\api_layers
```
The output from `api_dump` streams in my console window, so I believe that is working.  However,
right now there's an issue with the "library_path" attribute in the Layer manifest.  It can't just be the DLL name, nor can it be a relative path with UNIX directory separators (`/`), so my  "library_path" in `XrApiLayer_api_dump.json` is:
```
        "library_path": ".\\XrApiLayer_api_dump.dll",
```
I have a change pending that fixes relative paths with UNIX separators on Windows.
Can you share the .JSON file you're using?
Also, can you share the output with XR_LOADER_DEBUG turned on?

(12/4 fixed Julian's username)

**Comment by bradgrantham-lunarg** [comment] 2020-03-18 18:28
I use XR_API_LAYER_PATH on Windows to load the validation layer and a custom layer.  It appears to work.  I will close this by 3/26 unless @julianeisel or @SlimSnow  want to comment.

**Comment by bradgrantham-lunarg** [comment] 2020-03-25 15:51
No follow-up, can't reproduce, XR_API_LAYER_PATH appears to work just fine as documented.  Closing.

**Closed as completed by bradgrantham-lunarg** 2020-03-25 15:51 UTC
